[project]
name = "ap-reforco"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "gymnasium>=1.2.1",
    "matplotlib>=3.10.6",
    "numpy>=2.2.6",
    "seaborn>=0.13.2",
    "tqdm>=4.67.1",
]
